name: Push to Azure Container Registry

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.LOGIN_SERVER}}
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}
      - name: Build and push Docker image
        run: |
          docker build -t openapi-main:latest .
          docker tag openapi-main:latest ${{secrets.REGISTRY_NAME}}.azurecr.io/openapi-main
          docker push ${{secrets.REGISTRY_NAME}}.azurecr.io/openapi-main:latest
      - name: Clean up
        run: docker logout

